//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCMPWinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCMPWinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ajouter_act {
            get {
                object obj = ResourceManager.GetObject("ajouter_act", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap editer_act {
            get {
                object obj = ResourceManager.GetObject("editer_act", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap inscrire_act {
            get {
                object obj = ResourceManager.GetObject("inscrire_act", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap output_onlinepngtools {
            get {
                object obj = ResourceManager.GetObject("output_onlinepngtools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap output_onlinepngtools__1_ {
            get {
                object obj = ResourceManager.GetObject("output_onlinepngtools__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap output_onlinepngtools__2_ {
            get {
                object obj = ResourceManager.GetObject("output_onlinepngtools__2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap output_onlinepngtools__3_ {
            get {
                object obj = ResourceManager.GetObject("output_onlinepngtools__3_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap output_onlinepngtools__4_ {
            get {
                object obj = ResourceManager.GetObject("output_onlinepngtools__4_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap output_onlinepngtools__5_ {
            get {
                object obj = ResourceManager.GetObject("output_onlinepngtools__5_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap output_onlinepngtools__6_ {
            get {
                object obj = ResourceManager.GetObject("output_onlinepngtools__6_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap output_onlinepngtools__7_ {
            get {
                object obj = ResourceManager.GetObject("output_onlinepngtools__7_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://cda27.s1.2isa.org/upload/images/winform/.
        /// </summary>
        internal static string STR_ADRESSE_AVATAR {
            get {
                return ResourceManager.GetString("STR_ADRESSE_AVATAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1598527711.png.
        /// </summary>
        internal static string STR_AVATAR_PAR_DEFAUT {
            get {
                return ResourceManager.GetString("STR_AVATAR_PAR_DEFAUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;activité à bien été ajoutée.
        /// </summary>
        internal static string STR_MESSAGE_ACTIVITE_AJOUT_SUCCESS {
            get {
                return ResourceManager.GetString("STR_MESSAGE_ACTIVITE_AJOUT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adhérent {0} {1} a bien été ajouté.
        /// </summary>
        internal static string STR_MESSAGE_ADHERENT_BIEN_AJOUTE {
            get {
                return ResourceManager.GetString("STR_MESSAGE_ADHERENT_BIEN_AJOUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adresse mail saisie n&apos;est pas valide.
        /// </summary>
        internal static string STR_MESSAGE_ADRESSE_MAIL_NON_VALIDE {
            get {
                return ResourceManager.GetString("STR_MESSAGE_ADRESSE_MAIL_NON_VALIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adresse saisie est invalide.
        /// </summary>
        internal static string STR_MESSAGE_ADRESSE_NON_VALIDE {
            get {
                return ResourceManager.GetString("STR_MESSAGE_ADRESSE_NON_VALIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment annuler et fermer cette fenêtre ?.
        /// </summary>
        internal static string STR_MESSAGE_ANNULER_ET_FERMER {
            get {
                return ResourceManager.GetString("STR_MESSAGE_ANNULER_ET_FERMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un champs n&apos;est pas rempli.
        /// </summary>
        internal static string STR_MESSAGE_CHAMPS_NON_REMPLI {
            get {
                return ResourceManager.GetString("STR_MESSAGE_CHAMPS_NON_REMPLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le code postale saisie n&apos;est pas valide.
        /// </summary>
        internal static string STR_MESSAGE_CODEPOSTALE_NON_VALIDE {
            get {
                return ResourceManager.GetString("STR_MESSAGE_CODEPOSTALE_NON_VALIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment désinscrire {0} de l&apos;activité ?.
        /// </summary>
        internal static string STR_MESSAGE_CONFIRMATION_SUPPRESSION {
            get {
                return ResourceManager.GetString("STR_MESSAGE_CONFIRMATION_SUPPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de se connecter à la base de données, veuillez rééssayer plus tard....
        /// </summary>
        internal static string STR_MESSAGE_CONNEXION_BDD_ERROR {
            get {
                return ResourceManager.GetString("STR_MESSAGE_CONNEXION_BDD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La cylindrée saisie n&apos;est pas correcte (Seulement de 0 à 9999.).
        /// </summary>
        internal static string STR_MESSAGE_CYLINDREE_NON_VALIDE {
            get {
                return ResourceManager.GetString("STR_MESSAGE_CYLINDREE_NON_VALIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date de début doit être supérieur à la date d&apos;aujourd&apos;hui, la date limite doit être supérieur à la date de début ainsi qu&apos;inférieur à la date de fin et la date de fin doit être supérieur à la date limite..
        /// </summary>
        internal static string STR_MESSAGE_DATE_ACT_PROBLEME {
            get {
                return ResourceManager.GetString("STR_MESSAGE_DATE_ACT_PROBLEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La description doit contenir moins de 15000 caractères!.
        /// </summary>
        internal static string STR_MESSAGE_DESCRIPTION_PROBLEME {
            get {
                return ResourceManager.GetString("STR_MESSAGE_DESCRIPTION_PROBLEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La désinscription n&apos;a pas été réalisée.
        /// </summary>
        internal static string STR_MESSAGE_DESINSCRIPTION_ERREUR {
            get {
                return ResourceManager.GetString("STR_MESSAGE_DESINSCRIPTION_ERREUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adresse saisie est invalide.
        /// </summary>
        internal static string STR_MESSAGE_EMAIL_NON_VALIDE {
            get {
                return ResourceManager.GetString("STR_MESSAGE_EMAIL_NON_VALIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A propos doit être inférieur à 250 caractères.
        /// </summary>
        internal static string STR_MESSAGE_ERREUR_APROPOS {
            get {
                return ResourceManager.GetString("STR_MESSAGE_ERREUR_APROPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment fermer le programme ?.
        /// </summary>
        internal static string STR_MESSAGE_FERMER {
            get {
                return ResourceManager.GetString("STR_MESSAGE_FERMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de modifier le compte secrétaire.
        /// </summary>
        internal static string STR_MESSAGE_IMPOSSIBLE_MODIFIER_SECRETAIRE {
            get {
                return ResourceManager.GetString("STR_MESSAGE_IMPOSSIBLE_MODIFIER_SECRETAIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de supprimer le compte secrétaire.
        /// </summary>
        internal static string STR_MESSAGE_IMPOSSIBLE_SUPPRIMER_SECRETAIRE {
            get {
                return ResourceManager.GetString("STR_MESSAGE_IMPOSSIBLE_SUPPRIMER_SECRETAIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;inscription ne s&apos;est pas réalisée.
        /// </summary>
        internal static string STR_MESSAGE_INSCRIPTION_FAIL {
            get {
                return ResourceManager.GetString("STR_MESSAGE_INSCRIPTION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un adhérent porte déjà ce login.
        /// </summary>
        internal static string STR_MESSAGE_LOGIN_EXISTANT {
            get {
                return ResourceManager.GetString("STR_MESSAGE_LOGIN_EXISTANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le login doit être inférieur à 30 caractères.
        /// </summary>
        internal static string STR_MESSAGE_LOGIN_TROP_LONG {
            get {
                return ResourceManager.GetString("STR_MESSAGE_LOGIN_TROP_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La mise à jour ne s&apos;est pas réalisée.
        /// </summary>
        internal static string STR_MESSAGE_MAJ_NON_REALISEE {
            get {
                return ResourceManager.GetString("STR_MESSAGE_MAJ_NON_REALISEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La mise à jour s&apos;est bien réalisée.
        /// </summary>
        internal static string STR_MESSAGE_MAJ_OK {
            get {
                return ResourceManager.GetString("STR_MESSAGE_MAJ_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La modification a été réalisée.
        /// </summary>
        internal static string STR_MESSAGE_MODIFICATION_SUCCES {
            get {
                return ResourceManager.GetString("STR_MESSAGE_MODIFICATION_SUCCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nombre d&apos;invité(s) n&apos;est pas valide.
        /// </summary>
        internal static string STR_MESSAGE_NBINVITE_NONVALIDE {
            get {
                return ResourceManager.GetString("STR_MESSAGE_NBINVITE_NONVALIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom ou le prénom n&apos;est pas valide.
        /// </summary>
        internal static string STR_MESSAGE_NOM_NON_VALIDE {
            get {
                return ResourceManager.GetString("STR_MESSAGE_NOM_NON_VALIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le numéro de téléphone saisie n&apos;est pas valide (0XXXXXXXXX souhaité).
        /// </summary>
        internal static string STR_MESSAGE_NUMERO_NON_VALIDE {
            get {
                return ResourceManager.GetString("STR_MESSAGE_NUMERO_NON_VALIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Il y a un problème pour l&apos;ajout de cette activité.
        /// </summary>
        internal static string STR_MESSAGE_PROBLEME_AJOUT_ACT {
            get {
                return ResourceManager.GetString("STR_MESSAGE_PROBLEME_AJOUT_ACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Il y a un problème pour l&apos;ajout de l&apos;adhérent....
        /// </summary>
        internal static string STR_MESSAGE_PROBLEME_AJOUT_ADHERENT {
            get {
                return ResourceManager.GetString("STR_MESSAGE_PROBLEME_AJOUT_ADHERENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problème dans la modification de l&apos;adhérent.
        /// </summary>
        internal static string STR_MESSAGE_PROBLEME_MODIF_ADHERENT {
            get {
                return ResourceManager.GetString("STR_MESSAGE_PROBLEME_MODIF_ADHERENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Il y a un problème pour la suppression de l&apos;inscription.
        /// </summary>
        internal static string STR_MESSAGE_PROBLEME_SUPPRESSION_INSCRIPTION {
            get {
                return ResourceManager.GetString("STR_MESSAGE_PROBLEME_SUPPRESSION_INSCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment supprimer cette activité ?.
        /// </summary>
        internal static string STR_MESSAGE_SUPPRESSION_ACTIVITE {
            get {
                return ResourceManager.GetString("STR_MESSAGE_SUPPRESSION_ACTIVITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment supprimer {0} ?.
        /// </summary>
        internal static string STR_MESSAGE_SUPPRESSION_ADHERENT {
            get {
                return ResourceManager.GetString("STR_MESSAGE_SUPPRESSION_ADHERENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La suppression ne s&apos;est pas effectuée.
        /// </summary>
        internal static string STR_MESSAGE_SUPPRESSION_FAIL {
            get {
                return ResourceManager.GetString("STR_MESSAGE_SUPPRESSION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment supprimer cette inscription ?.
        /// </summary>
        internal static string STR_MESSAGE_SUPPRIMER_INSCRIPTION {
            get {
                return ResourceManager.GetString("STR_MESSAGE_SUPPRIMER_INSCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Il y a un problème avec les tarifs, merci de taper un tarif avec des chiffres et une seule virgule si besoin sans le symbole €..
        /// </summary>
        internal static string STR_MESSAGE_TARIF_PROBLEME {
            get {
                return ResourceManager.GetString("STR_MESSAGE_TARIF_PROBLEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La ville saisie est invalide.
        /// </summary>
        internal static string STR_MESSAGE_VILLE_NON_VALIDE {
            get {
                return ResourceManager.GetString("STR_MESSAGE_VILLE_NON_VALIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Succès.
        /// </summary>
        internal static string STR_TITRE_ACTIVITE_AJOUT_SUCCESS {
            get {
                return ResourceManager.GetString("STR_TITRE_ACTIVITE_AJOUT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adhérent ajouté !.
        /// </summary>
        internal static string STR_TITRE_ADHERENT_BIEN_AJOUTE {
            get {
                return ResourceManager.GetString("STR_TITRE_ADHERENT_BIEN_AJOUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur adresse email.
        /// </summary>
        internal static string STR_TITRE_ADRESSE_MAIL_NON_VALIDE {
            get {
                return ResourceManager.GetString("STR_TITRE_ADRESSE_MAIL_NON_VALIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse postale non valide.
        /// </summary>
        internal static string STR_TITRE_ADRESSE_NON_VALIDE {
            get {
                return ResourceManager.GetString("STR_TITRE_ADRESSE_NON_VALIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler et fermer ?.
        /// </summary>
        internal static string STR_TITRE_ANNULER_ET_FERMER {
            get {
                return ResourceManager.GetString("STR_TITRE_ANNULER_ET_FERMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Champs non-rempli.
        /// </summary>
        internal static string STR_TITRE_CHAMPS_NON_REMPLI {
            get {
                return ResourceManager.GetString("STR_TITRE_CHAMPS_NON_REMPLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur code postale.
        /// </summary>
        internal static string STR_TITRE_CODEPOSTALE_NON_VALIDE {
            get {
                return ResourceManager.GetString("STR_TITRE_CODEPOSTALE_NON_VALIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Désinscription de {0} {1}.
        /// </summary>
        internal static string STR_TITRE_CONFIRMATION_SUPPRESSION {
            get {
                return ResourceManager.GetString("STR_TITRE_CONFIRMATION_SUPPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Base de données injoingable.
        /// </summary>
        internal static string STR_TITRE_CONNEXION_BDD_ERROR {
            get {
                return ResourceManager.GetString("STR_TITRE_CONNEXION_BDD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur cylindrée.
        /// </summary>
        internal static string STR_TITRE_CYLINDREE_NON_VALIDE {
            get {
                return ResourceManager.GetString("STR_TITRE_CYLINDREE_NON_VALIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problème dans les dates.
        /// </summary>
        internal static string STR_TITRE_DATE_ACT_PROBLEME {
            get {
                return ResourceManager.GetString("STR_TITRE_DATE_ACT_PROBLEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problème dans la description.
        /// </summary>
        internal static string STR_TITRE_DESCRIPTION_PROBLEME {
            get {
                return ResourceManager.GetString("STR_TITRE_DESCRIPTION_PROBLEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string STR_TITRE_DESINSCRIPTION_ERREUR {
            get {
                return ResourceManager.GetString("STR_TITRE_DESINSCRIPTION_ERREUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur adresse mail.
        /// </summary>
        internal static string STR_TITRE_EMAIL_NON_VALIDE {
            get {
                return ResourceManager.GetString("STR_TITRE_EMAIL_NON_VALIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trop de caractères !.
        /// </summary>
        internal static string STR_TITRE_ERREUR_APROPOS {
            get {
                return ResourceManager.GetString("STR_TITRE_ERREUR_APROPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fermer.
        /// </summary>
        internal static string STR_TITRE_FERMER {
            get {
                return ResourceManager.GetString("STR_TITRE_FERMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible.
        /// </summary>
        internal static string STR_TITRE_IMPOSSIBLE_SUPPRIMER_SECRETAIRE {
            get {
                return ResourceManager.GetString("STR_TITRE_IMPOSSIBLE_SUPPRIMER_SECRETAIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string STR_TITRE_INSCRIPTION_FAIL {
            get {
                return ResourceManager.GetString("STR_TITRE_INSCRIPTION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login existant.
        /// </summary>
        internal static string STR_TITRE_LOGIN_EXISTANT {
            get {
                return ResourceManager.GetString("STR_TITRE_LOGIN_EXISTANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login trop long.
        /// </summary>
        internal static string STR_TITRE_LOGIN_TROP_LONG {
            get {
                return ResourceManager.GetString("STR_TITRE_LOGIN_TROP_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Echec.
        /// </summary>
        internal static string STR_TITRE_MAJ_NON_REALISEE {
            get {
                return ResourceManager.GetString("STR_TITRE_MAJ_NON_REALISEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise à jour terminée.
        /// </summary>
        internal static string STR_TITRE_MAJ_OK {
            get {
                return ResourceManager.GetString("STR_TITRE_MAJ_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification avec succès.
        /// </summary>
        internal static string STR_TITRE_MODIFICATION_SUCCES {
            get {
                return ResourceManager.GetString("STR_TITRE_MODIFICATION_SUCCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problème dans le nombre d&apos;invité(s).
        /// </summary>
        internal static string STR_TITRE_NBINVITE_NONVALIDE {
            get {
                return ResourceManager.GetString("STR_TITRE_NBINVITE_NONVALIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur nom ou prénom.
        /// </summary>
        internal static string STR_TITRE_NOM_NON_VALIDE {
            get {
                return ResourceManager.GetString("STR_TITRE_NOM_NON_VALIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur numéro de téléphone.
        /// </summary>
        internal static string STR_TITRE_NUMERO_NON_VALIDE {
            get {
                return ResourceManager.GetString("STR_TITRE_NUMERO_NON_VALIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problème d&apos;ajout.
        /// </summary>
        internal static string STR_TITRE_PROBLEME_AJOUT_ACT {
            get {
                return ResourceManager.GetString("STR_TITRE_PROBLEME_AJOUT_ACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problème d&apos;ajout.
        /// </summary>
        internal static string STR_TITRE_PROBLEME_AJOUT_ADHERENT {
            get {
                return ResourceManager.GetString("STR_TITRE_PROBLEME_AJOUT_ADHERENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problème de modification.
        /// </summary>
        internal static string STR_TITRE_PROBLEME_MODIF_ADHERENT {
            get {
                return ResourceManager.GetString("STR_TITRE_PROBLEME_MODIF_ADHERENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problème de suppression.
        /// </summary>
        internal static string STR_TITRE_PROBLEME_SUPPRESSION_INSCRIPTION {
            get {
                return ResourceManager.GetString("STR_TITRE_PROBLEME_SUPPRESSION_INSCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression de l&apos;activité.
        /// </summary>
        internal static string STR_TITRE_SUPPRESSION_ACTIVITE {
            get {
                return ResourceManager.GetString("STR_TITRE_SUPPRESSION_ACTIVITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression de {0} {1}.
        /// </summary>
        internal static string STR_TITRE_SUPPRESSION_ADHERENT {
            get {
                return ResourceManager.GetString("STR_TITRE_SUPPRESSION_ADHERENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string STR_TITRE_SUPPRESSION_FAIL {
            get {
                return ResourceManager.GetString("STR_TITRE_SUPPRESSION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression.
        /// </summary>
        internal static string STR_TITRE_SUPPRIMER_INSCRIPTION {
            get {
                return ResourceManager.GetString("STR_TITRE_SUPPRIMER_INSCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problème dans les tarifs.
        /// </summary>
        internal static string STR_TITRE_TARIF_PROBLEME {
            get {
                return ResourceManager.GetString("STR_TITRE_TARIF_PROBLEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur ville.
        /// </summary>
        internal static string STR_TITRE_VILLE_NON_VALIDE {
            get {
                return ResourceManager.GetString("STR_TITRE_VILLE_NON_VALIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap supprimer_act {
            get {
                object obj = ResourceManager.GetObject("supprimer_act", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unsubscribenews_1092__1_ {
            get {
                object obj = ResourceManager.GetObject("unsubscribenews_1092__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
