//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCMPWinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCMPWinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ajouter_act {
            get {
                object obj = ResourceManager.GetObject("ajouter_act", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap editer_act {
            get {
                object obj = ResourceManager.GetObject("editer_act", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap inscrire_act {
            get {
                object obj = ResourceManager.GetObject("inscrire_act", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap output_onlinepngtools {
            get {
                object obj = ResourceManager.GetObject("output_onlinepngtools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap output_onlinepngtools__1_ {
            get {
                object obj = ResourceManager.GetObject("output_onlinepngtools__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap output_onlinepngtools__2_ {
            get {
                object obj = ResourceManager.GetObject("output_onlinepngtools__2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap output_onlinepngtools__3_ {
            get {
                object obj = ResourceManager.GetObject("output_onlinepngtools__3_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap output_onlinepngtools__4_ {
            get {
                object obj = ResourceManager.GetObject("output_onlinepngtools__4_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap output_onlinepngtools__5_ {
            get {
                object obj = ResourceManager.GetObject("output_onlinepngtools__5_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap output_onlinepngtools__6_ {
            get {
                object obj = ResourceManager.GetObject("output_onlinepngtools__6_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap output_onlinepngtools__7_ {
            get {
                object obj = ResourceManager.GetObject("output_onlinepngtools__7_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://cda27.s1.2isa.org/upload/images/winform/.
        /// </summary>
        internal static string STR_ADRESSE_AVATAR {
            get {
                return ResourceManager.GetString("STR_ADRESSE_AVATAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1598527711.png.
        /// </summary>
        internal static string STR_AVATAR_PAR_DEFAUT {
            get {
                return ResourceManager.GetString("STR_AVATAR_PAR_DEFAUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment désinscrire {1} de l&apos;activité ?.
        /// </summary>
        internal static string STR_MESSAGE_CONFIRMATION_SUPPRESSION {
            get {
                return ResourceManager.GetString("STR_MESSAGE_CONFIRMATION_SUPPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La désinscription n&apos;a pas été réalisée.
        /// </summary>
        internal static string STR_MESSAGE_DESINSCRIPTION_ERREUR {
            get {
                return ResourceManager.GetString("STR_MESSAGE_DESINSCRIPTION_ERREUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment fermer le programme ?.
        /// </summary>
        internal static string STR_MESSAGE_FERMER {
            get {
                return ResourceManager.GetString("STR_MESSAGE_FERMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Il y a un problème pour la suppression de l&apos;inscription.
        /// </summary>
        internal static string STR_MESSAGE_PROBLEME_SUPPRESSION_INSCRIPTION {
            get {
                return ResourceManager.GetString("STR_MESSAGE_PROBLEME_SUPPRESSION_INSCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment supprimer {1} ?.
        /// </summary>
        internal static string STR_MESSAGE_SUPPRESSION_ADHERENT {
            get {
                return ResourceManager.GetString("STR_MESSAGE_SUPPRESSION_ADHERENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La suppression ne s&apos;est pas effectuée.
        /// </summary>
        internal static string STR_MESSAGE_SUPPRESSION_FAIL {
            get {
                return ResourceManager.GetString("STR_MESSAGE_SUPPRESSION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment supprimer cette inscription ?.
        /// </summary>
        internal static string STR_MESSAGE_SUPPRIMER_INSCRIPTION {
            get {
                return ResourceManager.GetString("STR_MESSAGE_SUPPRIMER_INSCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Désinscription de {1} {2}.
        /// </summary>
        internal static string STR_TITRE_CONFIRMATION_SUPPRESSION {
            get {
                return ResourceManager.GetString("STR_TITRE_CONFIRMATION_SUPPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string STR_TITRE_DESINSCRIPTION_ERREUR {
            get {
                return ResourceManager.GetString("STR_TITRE_DESINSCRIPTION_ERREUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fermer.
        /// </summary>
        internal static string STR_TITRE_FERMER {
            get {
                return ResourceManager.GetString("STR_TITRE_FERMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problème de suppression.
        /// </summary>
        internal static string STR_TITRE_PROBLEME_SUPPRESSION_INSCRIPTION {
            get {
                return ResourceManager.GetString("STR_TITRE_PROBLEME_SUPPRESSION_INSCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression de {1} {2}.
        /// </summary>
        internal static string STR_TITRE_SUPPRESSION_ADHERENT {
            get {
                return ResourceManager.GetString("STR_TITRE_SUPPRESSION_ADHERENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string STR_TITRE_SUPPRESSION_FAIL {
            get {
                return ResourceManager.GetString("STR_TITRE_SUPPRESSION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression.
        /// </summary>
        internal static string STR_TITRE_SUPPRIMER_INSCRIPTION {
            get {
                return ResourceManager.GetString("STR_TITRE_SUPPRIMER_INSCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap supprimer_act {
            get {
                object obj = ResourceManager.GetObject("supprimer_act", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unsubscribenews_1092__1_ {
            get {
                object obj = ResourceManager.GetObject("unsubscribenews_1092__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
